name: Semantic Release
on:
  push:
    branches:
      - main
      - alpha
      - beta
      - "*.*.*"
      - "*.*"

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Git access
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "derobertis.nick@gmail.com"
          git config --global user.name "Nick DeRobertis"
          gh auth setup-git
          gh auth status
          curl -sS -f -I -H "Authorization: token ${GH_TOKEN}" https://api.github.com | grep ^x-oauth-scopes: | cut -d' ' -f2- | tr -d "[:space:]" | tr ',' '\n'
          git ls-remote https://github.com/nickderobertis/flexlate-dev-semantic-release-example
          git push --dry-run --no-verify https://x-access-token:$GH_TOKEN@github.com/nickderobertis/flexlate-dev-semantic-release-example HEAD:main
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
